In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#importing csv dataset
data=pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv',encoding='latin-1')

In [3]:
data

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [4]:
data.info

<bound method DataFrame.info of        Area Code      Area  Item Code           Item  Element Code  \
0              4   Algeria       2501     Population           511
1              4   Algeria       2501     Population          5301
2              4   Algeria       2901    Grand Total           664
3              4   Algeria       2901    Grand Total           674
4              4   Algeria       2901    Grand Total           684
...          ...       ...        ...            ...           ...
60938        181  Zimbabwe       2899  Miscellaneous          5142
60939        181  Zimbabwe       2899  Miscellaneous           645
60940        181  Zimbabwe       2899  Miscellaneous           664
60941        181  Zimbabwe       2899  Miscellaneous           674
60942        181  Zimbabwe       2899  Miscellaneous           684

                                      Element             Unit     Y2014  \
0               Total Population - Both sexes     1000 persons  38924.00
1                    Domestic supply quantity      1000 tonnes      0.00
2               Food supply (kcal/capita/day)  kcal/capita/day   3377.00
3      Protein supply quantity (g/capita/day)     g/capita/day     94.90
4          Fat supply quantity (g/capita/day)     g/capita/day     80.06
...                                       ...              ...       ...
60938                                    Food      1000 tonnes     42.00
60939     Food supply quantity (kg/capita/yr)               kg      3.06
60940           Food supply (kcal/capita/day)  kcal/capita/day      3.00
60941  Protein supply quantity (g/capita/day)     g/capita/day      0.10
60942      Fat supply quantity (g/capita/day)     g/capita/day      0.04

          Y2015     Y2016     Y2017     Y2018
0      39728.00  40551.00  41389.00  42228.00
1          0.00      0.00      0.00      0.00
2       3379.00   3372.00   3341.00   3322.00
3         94.35     94.72     92.82     91.83
4         79.36     77.40     80.19     77.28
...         ...       ...       ...       ...
60938     46.00     33.00     19.00     16.00
60939      3.33      2.35      1.33      1.08
60940      4.00      3.00      1.00      1.00
60941      0.11      0.08      0.04      0.04
60942      0.05      0.03      0.02      0.01

[60943 rows x 12 columns]>

In [5]:
correlation_matrix = data.corr()

<ipython-input-5-19e8f3752a40>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = data.corr()

In [6]:
print(correlation_matrix)

              Area Code  Item Code  Element Code     Y2014     Y2015  \
Area Code      1.000000  -0.005159     -0.000209  0.006164  0.005472
Item Code     -0.005159   1.000000     -0.024683  0.021722  0.020857
Element Code  -0.000209  -0.024683      1.000000  0.024457  0.023889
Y2014          0.006164   0.021722      0.024457  1.000000  0.994647
Y2015          0.005472   0.020857      0.023889  0.994647  1.000000
Y2016          0.005247   0.020109      0.023444  0.996081  0.995739
Y2017          0.005006   0.021494      0.024254  0.995230  0.988048
Y2018          0.005665   0.021314      0.024279  0.994872  0.988208

                 Y2016     Y2017     Y2018
Area Code     0.005247  0.005006  0.005665
Item Code     0.020109  0.021494  0.021314
Element Code  0.023444  0.024254  0.024279
Y2014         0.996081  0.995230  0.994872
Y2015         0.995739  0.988048  0.988208
Y2016         1.000000  0.992785  0.992757
Y2017         0.992785  1.000000  0.998103
Y2018         0.992757  0.998103  1.000000

In [7]:
data['Element'].count()

60943

In [8]:
# Filter data for Madagascar and the year 2015
madagascar_2015 = data[(data['Area'] == 'Madagascar') & (data['Y2015'])]

In [9]:
print(madagascar_2015)

       Area Code        Area  Item Code              Item  Element Code  \
30715        129  Madagascar       2501        Population           511
30717        129  Madagascar       2901       Grand Total           664
30718        129  Madagascar       2901       Grand Total           674
30719        129  Madagascar       2901       Grand Total           684
30720        129  Madagascar       2903  Vegetal Products           664
...          ...         ...        ...               ...           ...
32147        129  Madagascar       2899     Miscellaneous          5301
32149        129  Madagascar       2899     Miscellaneous          5142
32150        129  Madagascar       2899     Miscellaneous           645
32152        129  Madagascar       2899     Miscellaneous           674
32153        129  Madagascar       2899     Miscellaneous           684

                                      Element             Unit     Y2014  \
30715           Total Population - Both sexes     1000 persons  23590.00
30717           Food supply (kcal/capita/day)  kcal/capita/day   1986.00
30718  Protein supply quantity (g/capita/day)     g/capita/day     44.45
30719      Fat supply quantity (g/capita/day)     g/capita/day     22.18
30720           Food supply (kcal/capita/day)  kcal/capita/day   1853.00
...                                       ...              ...       ...
32147                Domestic supply quantity      1000 tonnes     10.00
32149                                    Food      1000 tonnes     10.00
32150     Food supply quantity (kg/capita/yr)               kg      0.44
32152  Protein supply quantity (g/capita/day)     g/capita/day      0.01
32153      Fat supply quantity (g/capita/day)     g/capita/day      0.01

          Y2015     Y2016     Y2017     Y2018
30715  24234.00  24894.00  25571.00  26262.00
30717   1922.00   1918.00   1943.00   1938.00
30718     43.26     43.35     43.94     44.17
30719     22.97     23.83     25.26     24.12
30720   1788.00   1782.00   1808.00   1804.00
...         ...       ...       ...       ...
32147     11.00     11.00     11.00     12.00
32149     11.00     11.00     11.00     12.00
32150      0.44      0.44      0.44      0.44
32152      0.01      0.01      0.01      0.01
32153      0.01      0.01      0.01      0.01

[783 rows x 12 columns]

In [10]:
# Sum the 'Protein_Supply_Quantity' column for Madagascar in 2015
total_protein_supply = madagascar_2015.sum()

In [11]:
print(total_protein_supply)

Area Code                                                  101007
Area            MadagascarMadagascarMadagascarMadagascarMadaga...
Item Code                                                 2128948
Item            PopulationGrand TotalGrand TotalGrand TotalVeg...
Element Code                                              2811467
Element         Total Population - Both sexesFood supply (kcal...
Unit            1000 personskcal/capita/dayg/capita/dayg/capit...
Y2014                                                   128985.25
Y2015                                                    126674.9
Y2016                                                   128952.17
Y2017                                                   131075.68
Y2018                                                   134434.33
dtype: object

In [12]:
sum1 = data.groupby(['Y2015', 'Y2018']).sum()

<ipython-input-12-e97910279b0b>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sum1 = data.groupby(['Y2015', 'Y2018']).sum()

In [13]:
sum1

,,Area Code,Item Code,Element Code,Y2014,Y2016,Y2017
Y2015,Y2018,,,,,,
-3161.0,-296.0,202,2905,5072,439.0,-1499.0,2665.0
-2152.0,-597.0,202,2514,5072,626.0,-1324.0,2555.0
-1284.0,1898.0,276,2905,5072,4569.0,3266.0,-607.0
-907.0,-529.0,251,2905,5072,520.0,-506.0,532.0
-887.0,163.0,276,2518,5072,3134.0,2432.0,-819.0
...,...,...,...,...,...,...,...
92443.0,98424.0,59,2501,511,90425.0,94447.0,96443.0
100835.0,109224.0,238,2501,511,98094.0,103603.0,106400.0
110798.0,117038.0,159,2907,5301,108756.0,116483.0,112625.0
111663.0,118172.0,159,2907,5511,109593.0,119330.0,117702.0
181137.0,195875.0,159,2501,511,176405.0,185960.0,190873.0

In [14]:
total_sum = data[['Y2015', 'Y2018']].sum()
print(total_sum)

Y2015    8032340.23
Y2018    8554629.96
dtype: float64

In [15]:
data.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [16]:
data['Y2017'].mean()

140.9177648602722

In [17]:
data['Y2017'].std()

1671.8623590567995

In [18]:
S = [['him', 'sell'], [90, 28, 43]]
S[0][1][1]

'e'

In [19]:
data['Area'].count()

60943

In [20]:
data.shape

(60943, 12)

In [21]:
data.groupby(['Area', 'Y2017']).sum()

<ipython-input-21-92e6230fdde2>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby(['Area', 'Y2017']).sum()

                   Area Code  Item Code  Element Code    Y2014    Y2015  \
Area     Y2017
Algeria  -81.0             8       5536         10144     60.0    -10.0
         -47.0             8       5438         10144    312.0     70.0
         -11.0             4       2563          5072    -29.0    -11.0
         -6.0              4       2680          5072      1.0      4.0
         -5.0             12       8257         15412    -24.0    -24.0
...                      ...        ...           ...      ...      ...
Zimbabwe  1891.0         181       2901           664   1986.0   1912.0
          2209.0         181       2905          5301   2013.0   1851.0
          3101.0         724      10888         21624  15424.0  13392.0
          3452.0         362       5444         10262   7570.0   7104.0
          14237.0        181       2501           511  13587.0  13815.0

                     Y2016    Y2018
Area     Y2017
Algeria  -81.0      -121.0      0.0
         -47.0       122.0   -180.0
         -11.0        23.0     34.0
         -6.0          1.0      0.0
         -5.0        -28.0     -4.0
...                    ...      ...
Zimbabwe  1891.0    1885.0   1908.0
          2209.0    1940.0   2071.0
          3101.0   13932.0  14240.0
          3452.0    7456.0   7338.0
          14237.0  14030.0  14439.0

[14773 rows x 7 columns]

In [22]:
data.groupby(['Element']).sum()

<ipython-input-22-3464703521ca>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby(['Element']).sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00